### ISSUE TITLE
disp regressor aplication is delteing theta_deg without replacing it

### ISSUE THREAD

**Issue by jebuss** [fact-project/classifier-tools#41]
This has the consequence that a data sample on which the disp regression was applied, does not contain `theta_deg` anymore.

see: `classifier-tools.klaas.scripts.apply_disp_regressor.py`
```
columns_to_delete = [
        'source_x_prediction',
        'source_y_prediction',
        'theta',
        'theta_deg',
        'theta_rec_pos',
        'disp_prediction',
    ]
````
in https://github.com/fact-project/fact_plots/blob/master/fact_plots/scripts/plot_effective_area.py this feature is hardcoded and thus not availiable after disp regression.

see also: https://github.com/fact-project/fact_plots/issues/14

**Comment by MaxNoe** [comment]
Yes, this was intentionally done in #33

**Comment by jebuss** [comment]
I see. Since I ran into this problem due to missing knowledge, I think it make sense to document this together with the disp-regressor.
