### ISSUE TITLE
How to ensure reproducibility

### ISSUE THREAD

**Issue by mackaiver** [fact-project/classifier-tools#5]
Since PR #1  we have 2 "configuration" files that define the complete separation process.  One for the cuts and one for the classifier settings. Together with the input to fact-tools (i.e. the xml) and the exact call to Erna its probably more like 4 "config"  file would you agree? So I think were closer than ever to create some reliable way to define our complete analysis process. Maybe we can collect ideas on how to handle this here (or somewehre else I don't care).

One idea I had is simply to use a combination Makefiles, Config Files, and Git tags. So maybe a new repository which defines the analysis *Pass* (you know. as in Fermi). It would also need somekind of `requirements.txt` to specify the version numbers. Or maybe even a dockerfile?

I don't think this has a huge priority but I wanted to drop this here before it gets forgotten.

**Comment by MaxNoe** [comment]
Have a look here, I'm in the process of starting this for the high level stuff: https://github.com/fact-project/mrk501-2014-analysis

**Comment by MaxNoe** [comment]
I think this is now achieved by using Makefiles, fixed versions and random seeds like here https://github.com/fact-porject/open_crab_sample_analysis
