### ISSUE TITLE
Rename Module

### ISSUE THREAD

**Issue by mackaiver** [fact-project/classifier-tools#6]
I don't like klaas anymore.
Can we find something spelling out _helge_?
I'm quite serious.

**Comment by dneise** [comment]
Something with *H*igh *E*nergy ... ?

**Comment by MaxNoe** [comment]
**H**igh **E**nergy Machine **L**earning **G**amma-Ray **E**stimation ?

**Comment by mackaiver** [comment]
I guess thats not going to happen after all. We need a new project called  helge then.

**Comment by MaxNoe** [comment]
We just renamed to `aict-tools`
